### PR TITLE
Multiple edits

### PR DESCRIPTION
**Pull request by UndecidedSource**
- Use channel ID instead of name (therefore the user can always change the name of the suggestion channel with no worries)
- Destructuring
- Remove extra client.login

### CODE REVIEW

**Comment by loertis** [comment]
> * Use channel ID instead of name (therefore the user can always change the name of the suggestion channel with no worries)
> * Destructuring
> * Remove extra client.login

**Comment by UndecidedSource** [comment]
what

**Comment by lumeyisnotyou** [comment]
um this is improving the software, not requesting warranty on it lol

**Comment by loertis** [comment]
it's provided as-is lol

**Pull request merged**
